<?php

use Illuminate\Database\Seeder;

class ExternalTxSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('external_tx_types')->delete();

        $external_tx = array(

            array('description' =>'CARGO PAGO M','tx' =>'PAGO','bank_id' =>7, 'reference' =>'042D', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'CARGO COM MA','tx' =>'COM','bank_id' =>7, 'reference' =>'043D', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'CARGO POR APERTURA C','tx' =>'PAGO','bank_id' =>7, 'reference' =>'620D', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'CARGO DOMICILIA','tx' =>'PAGO','bank_id' =>7, 'reference' =>'838D', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COBRO COMISION BBVA','tx' =>'COM','bank_id' =>7, 'reference' =>'860D', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COBRO IVA COMISION B','tx' =>'IVA','bank_id' =>7, 'reference' =>'861D', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'ABONO POR DOMIC','tx' =>'REC','bank_id' =>7, 'reference' =>'954H', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION POR DO','tx' =>'COM','bank_id' =>7, 'reference' =>'955D', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'IVA POR COMISIO','tx' =>'IVA','bank_id' =>7, 'reference' =>'956D', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'DEVOLUCION CARG','tx' =>'DEV','bank_id' =>7, 'reference' =>'957H', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'COBRO DE TOKEN','tx' =>'COM','bank_id' =>13, 'reference' =>'CDT', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'NOTA DEBITO CHEQUE D','tx' =>'CH','bank_id' =>13, 'reference' =>'CHD', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'NOTA DEBITO IMPUESTO','tx' =>'GMF','bank_id' =>13, 'reference' =>'COP', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION PORTES CHEQ','tx' =>'COM','bank_id' =>13, 'reference' =>'CRR', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION RECAUDO RED','tx' =>'COM','bank_id' =>13, 'reference' =>'CSF', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION RECAUDO CNB','tx' =>'COM','bank_id' =>13, 'reference' =>'CSG', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'NC RECAUDO  RED CERC','tx' =>'REC','bank_id' =>13, 'reference' =>'CSJ', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'NC RECAUDO CNB','tx' =>'REC','bank_id' =>13, 'reference' =>'CSK', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'NC RECAUDO CNB','tx' =>'REC','bank_id' =>13, 'reference' =>'CSL', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION SERVICIO RE','tx' =>'COM','bank_id' =>13, 'reference' =>'CSV', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COM. DEPOSITO NAL CO','tx' =>'COM','bank_id' =>13, 'reference' =>'CTN', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'DEPOSITO CON COMP ES','tx' =>'REC','bank_id' =>13, 'reference' =>'DEE', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'DEB PAGO NOMINA','tx' =>'PAGO','bank_id' =>13, 'reference' =>'DPN', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'CREDITO VARIO','tx' =>'NCV','bank_id' =>13, 'reference' =>'GMI', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'ND IMPUESTO FINANCIE','tx' =>'GMF','bank_id' =>13, 'reference' =>'GMI', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'INTERESES POR SOBREG','tx' =>'INSG','bank_id' =>13, 'reference' =>'INS', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'NOTA DEBITO I.V.A.','tx' =>'IVA','bank_id' =>13, 'reference' =>'IVA', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'NOTA CREDITO','tx' =>'REC','bank_id' =>13, 'reference' =>'NC', 'sign' =>'C', 'type' =>'SIMPLE'),
            array('description' =>'TRANF DESDE    00000','tx' =>'TRAS','bank_id' =>13, 'reference' =>'NCF', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'NOTA DEBITO','tx' =>'PAGO','bank_id' =>13, 'reference' =>'ND', 'sign' =>'D', 'type' =>'SIMPLE'),
            array('description' =>'NC TRANS ACH ','tx' =>'REC','bank_id' =>13, 'reference' =>'NTA', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO DDDEDO PSP','tx' =>'REC','bank_id' =>13, 'reference' =>'PSU', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PROVISION POR TRANSP','tx' =>'TRAS','bank_id' =>13, 'reference' =>'PTW', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'NOTA CREDITO RECAUDO','tx' =>'REC','bank_id' =>13, 'reference' =>'RCC', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'NOTA CREDITO RECAUDO','tx' =>'REC','bank_id' =>13, 'reference' =>'RCI', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'NC RECAUDOS RED ATH','tx' =>'REC','bank_id' =>13, 'reference' =>'RCT', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'NC RECAUDO AVALNET','tx' =>'REC','bank_id' =>13, 'reference' =>'RCV', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION POR RECAUDO','tx' =>'COM','bank_id' =>13, 'reference' =>'REA', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO CHEQUE POR CANJ','tx' =>'CH','bank_id' =>13, 'reference' =>'RPC', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'RECAUDO POR TRANSPOR','tx' =>'REC','bank_id' =>13, 'reference' =>'RTD', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'ND TRANF ACH AUTORIZ','tx' =>'TRAS','bank_id' =>13, 'reference' =>'TAS', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'NC TRANSF. AVALNET','tx' =>'TRAS','bank_id' =>13, 'reference' =>'TCI', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'ND TRANSF. AVALNET','tx' =>'TRAS','bank_id' =>13, 'reference' =>'TDI', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'CRE PAGO PROVEEDOR','tx' =>'REC','bank_id' =>13, 'reference' =>'CPR', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CONSIG NAL REFERENC ','tx' =>'REC','bank_id' =>4, 'reference' =>'0525', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'COMIS RECAUDO CAJERO','tx' =>'COM','bank_id' =>4, 'reference' =>'0573', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION CAJEROS COD','tx' =>'COM','bank_id' =>4, 'reference' =>'0577', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'IVA COMISION RECAUDO','tx' =>'IVA','bank_id' =>4, 'reference' =>'0601', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COBRO COMISION ACH C','tx' =>'COM','bank_id' =>4, 'reference' =>'0609', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION CB CODIGO D','tx' =>'COM','bank_id' =>4, 'reference' =>'0815', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'IVA COMISION RECAUDO','tx' =>'IVA','bank_id' =>4, 'reference' =>'0823', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRANSF. CTAS. PROP','tx' =>'TRAS','bank_id' =>4, 'reference' =>'0841', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRANSF. CTAS. PROP','tx' =>'TRAS','bank_id' =>4, 'reference' =>'0843', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'DEVOLUCION CONSIGNAC','tx' =>'DEV','bank_id' =>4, 'reference' =>'1007', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COBRO IVA PAGOS AUTO','tx' =>'IVA','bank_id' =>4, 'reference' =>'1233', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'DEVOL ANUL CHEQ GERE','tx' =>'DEV','bank_id' =>4, 'reference' =>'1269', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'DEV IVA COMIS EXPED ','tx' =>'IVA','bank_id' =>4, 'reference' =>'1334', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION CAJA CODIGO','tx' =>'COM','bank_id' =>4, 'reference' =>'1340', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMIS PAGOS SUC VIRT','tx' =>'COM','bank_id' =>4, 'reference' =>'1627', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMIS IVA PAGOS SUC ','tx' =>'COM','bank_id' =>4, 'reference' =>'1630', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO IMP DIAN PSE - ','tx' =>'PAGO','bank_id' =>4, 'reference' =>'2188', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'ABONO CREDIPAGO SUC ','tx' =>'REC','bank_id' =>4, 'reference' =>'2252', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'TRASLADO DE ENCARGO','tx' =>'TRAS','bank_id' =>4, 'reference' =>'2934', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'DB GENERICO EXENTO G','tx' =>'NDV','bank_id' =>4, 'reference' =>'3014', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'CORRECCION DB CANJE','tx' =>'NDV','bank_id' =>4, 'reference' =>'3017', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'ABONO CARTERA SUC VI','tx' =>'PAGO','bank_id' =>4, 'reference' =>'3046', 'sign' =>'D', 'type' =>'SIMPLE'),
            array('description' =>'GRAVAMEN MOVIMIENTO ','tx' =>'GMF','bank_id' =>4, 'reference' =>'3339', 'sign' =>'D', 'type' =>'SIMPLE'),
            array('description' =>'PAGO VIRTUAL PSE','tx' =>'REC','bank_id' =>4, 'reference' =>'3579', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CONSIG LOCAL REFEREN','tx' =>'REC','bank_id' =>4, 'reference' =>'4013', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CONSIG LOCAL REFEREN','tx' =>'REC','bank_id' =>4, 'reference' =>'4014', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CONSIG NAL REFERENCI','tx' =>'REC','bank_id' =>4, 'reference' =>'4017', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CONSIG NAL REFERENCI','tx' =>'REC','bank_id' =>4, 'reference' =>'4018', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CUOTA MANEJO CUPO RO','tx' =>'COM','bank_id' =>4, 'reference' =>'4025', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRASLADO DE ENCARGO ','tx' =>'TRAS','bank_id' =>4, 'reference' =>'4060', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'TRANSFERENCIA','tx' =>'TRAS','bank_id' =>4, 'reference' =>'4152', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'TRASLADO CTA BANCOL','tx' =>'TRAS','bank_id' =>4, 'reference' =>'4155', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'TRASLADO CTAS BANCOL','tx' =>'TRAS','bank_id' =>4, 'reference' =>'4160', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'TRASL CTAS BANCOL PA','tx' =>'TRAS','bank_id' =>4, 'reference' =>'4165', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION PSE','tx' =>'COM','bank_id' =>4, 'reference' =>'4175', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'IVA COMISION PSE','tx' =>'IVA','bank_id' =>4, 'reference' =>'4178', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO EN CHEQ','tx' =>'CH','bank_id' =>4, 'reference' =>'4364', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION PAGOS EN CH','tx' =>'COM','bank_id' =>4, 'reference' =>'4733', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'CHEQUE GIRADO','tx' =>'CH','bank_id' =>4, 'reference' =>'5000', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION RECAUDOS CA','tx' =>'COM','bank_id' =>4, 'reference' =>'5537', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMIS RECAUDOS CAJA ','tx' =>'COM','bank_id' =>4, 'reference' =>'5539', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'DEV COMIS EXPED CHEQ','tx' =>'DCOM','bank_id' =>4, 'reference' =>'6557', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CONSIG REFER BCA ELE','tx' =>'REC','bank_id' =>4, 'reference' =>'6842', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'COMPRA CHEQUE DE GER','tx' =>'CHG','bank_id' =>4, 'reference' =>'7019', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'DEVOLUCION CHEQUE CO','tx' =>'DEV','bank_id' =>4, 'reference' =>'7081', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRASLADO CREDITO PIN','tx' =>'REC','bank_id' =>4, 'reference' =>'7111', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'ABONO VISA SUC.VIRTU','tx' =>'PAGO','bank_id' =>4, 'reference' =>'7139', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO A PROV','tx' =>'PAGO','bank_id' =>4, 'reference' =>'7160', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMIS SERVICIOS DE R','tx' =>'COM','bank_id' =>4, 'reference' =>'7181', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'INTERESES DE SOBREGI','tx' =>'INSG','bank_id' =>4, 'reference' =>'7251', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION PAGO A PROV','tx' =>'COM','bank_id' =>4, 'reference' =>'7371', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'IVA CUOTA MANEJO CUP','tx' =>'IVA','bank_id' =>4, 'reference' =>'7487', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO PSE ','tx' =>'PAGO','bank_id' =>4, 'reference' =>'7493', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO SERVICIOS','tx' =>'PAGO','bank_id' =>4, 'reference' =>'7511', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'COMISION PAGOS A TER','tx' =>'COM','bank_id' =>4, 'reference' =>'7524', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'IVA COMISION RECAUDO','tx' =>'IVA','bank_id' =>4, 'reference' =>'7525', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO RECAUDO ','tx' =>'REC','bank_id' =>4, 'reference' =>'7537', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO ACUEDUCTO ','tx' =>'PAGO','bank_id' =>4, 'reference' =>'7540', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO ENERGIA','tx' =>'PAGO','bank_id' =>4, 'reference' =>'7542', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO COMUNICAC ','tx' =>'PAGO','bank_id' =>4, 'reference' =>'7544', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'DEBITO AUTOMAT UNE','tx' =>'PAGO','bank_id' =>4, 'reference' =>'7552', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'DB DIF EN VR CONSIG ','tx' =>'NDV','bank_id' =>4, 'reference' =>'7657', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'DB CONSIG NO RECIBID','tx' =>'NDV','bank_id' =>4, 'reference' =>'7658', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRANSFERENCIA DESDE','tx' =>'TRAS','bank_id' =>4, 'reference' =>'7891', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'ABONO CANCELACION CD','tx' =>'REC','bank_id' =>4, 'reference' =>'8028', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'ABONO CANCELACION CD','tx' =>'REC','bank_id' =>4, 'reference' =>'80288', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CORRECCION CREDITO','tx' =>'NCV','bank_id' =>4, 'reference' =>'8035', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'TRASLADO DEPOSITO EN','tx' =>'TRAS','bank_id' =>4, 'reference' =>'8077', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CORRECCION CR OPERAC','tx' =>'NCV','bank_id' =>4, 'reference' =>'8100', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'TRASL ENTRE FONDOS D','tx' =>'TRAS','bank_id' =>4, 'reference' =>'8112', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO DE NOM ','tx' =>'REC','bank_id' =>4, 'reference' =>'8140', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO DE TERC','tx' =>'REC','bank_id' =>4, 'reference' =>'8141', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO INTERBANC ','tx' =>'REC','bank_id' =>4, 'reference' =>'8142', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO NO APLICADO ','tx' =>'REC','bank_id' =>4, 'reference' =>'8143', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO INTERBANC ANGEL','tx' =>'REC','bank_id' =>4, 'reference' =>'8146', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO DE PROV','tx' =>'REC','bank_id' =>4, 'reference' =>'8161', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CR CONSIGNACION SIN ','tx' =>'REC','bank_id' =>4, 'reference' =>'8359', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'IVA POR SERVICIO DE ','tx' =>'IVA','bank_id' =>4, 'reference' =>'9333', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRASLADO A SU CUENTA','tx' =>'TRAS','bank_id' =>4, 'reference' =>'3528', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'RECHAZO DE DEBITO ENVIADO','tx' =>'DEV','bank_id' =>11, 'reference' =>'', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRA.FON.BVE A-121082330','tx' =>'TRAS','bank_id' =>11, 'reference' =>'', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRA.FON.BVE A-124190134','tx' =>'TRAS','bank_id' =>11, 'reference' =>'', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'PAGOS ELECTRONICOS','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CREDITO RECIBIDO ACH          ','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CR Recaudo ACH DEBITO CUOTA','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'NT CRE AJT RECAUDO OF/CENTRALI','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'TRA. FON. BVE DE-124190134','tx' =>'TRAS','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'Trasla Env (1) TIT.Core/CIT ..','tx' =>'TRAS','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'Deb Origin Ach DEBITO CUOTA','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'Rec.Inter TFR TO-4582002339','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'Pago de ProveedAbono cuenta Co','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'Rec.Inter TFR TO-4662023582','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CREDITO RECIBIDO ACH','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'Consignación efectivo','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>' Consignación cheque No. 1','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'DEP.Efec. 4581013529','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'Rec.Inter TFR TO-4292006924','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'4802024563','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'Rec.Inter TFR TO-182002363','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO DE INTERES GENERADO POR E','tx' =>'REC','bank_id' =>11, 'reference' =>'', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CODIGO DE BARRAS','tx' =>'REC','bank_id' =>8, 'reference' =>'805', 'sign' =>'C', 'type' =>'SIMPLE'),
            array('description' =>'COMISION CODIGO DE BARRAS','tx' =>'COM','bank_id' =>8, 'reference' =>'1103', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'IVA COBRADO','tx' =>'IVA','bank_id' =>8, 'reference' =>'5503', 'sign' =>'D', 'type' =>'SIMPLE'),
            array('description' =>'TRANSFERENCIA DB OCCIRED','tx' =>'TRAS','bank_id' =>8, 'reference' =>'2003', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'TRANSF ENTRE CTAS OCCIDENTE','tx' =>'TRAS','bank_id' =>8, 'reference' =>'2005', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'GMF','tx' =>'GMF','bank_id' =>8, 'reference' =>'2903', 'sign' =>'D', 'type' =>'SIMPLE'),
            array('description' =>'CUOTA DE MANEJO RED PUBLICA INTERNET','tx' =>'COM','bank_id' =>8, 'reference' =>'6503', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'RECAUDO/PAGO SERVICIOS ELECT','tx' =>'REC','bank_id' =>8, 'reference' =>'1105', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'PAGO TERCERO RECIBIDO DESDE ACH','tx' =>'REC','bank_id' =>8, 'reference' =>'9205', 'sign' =>'C', 'type' =>'COMPUESTA'),
            array('description' =>'CARGO POR OTROS CONCEPTOS SIN GMF','tx' =>'COM','bank_id' =>8, 'reference' =>'8203', 'sign' =>'D', 'type' =>'COMPUESTA'),
            array('description' =>'SIN MOVIMIENTO DEBITO','tx' =>'SMVD','bank_id' =>8, 'reference' =>'', 'sign' =>'D', 'type' =>'SIMPLE'),
            array('description' =>'SIN MOVIMIENTO CREDITO','tx' =>'SMVC','bank_id' =>8, 'reference' =>'', 'sign' =>'C', 'type' =>'SIMPLE'),


            
        );

        DB::table('external_tx_types')->insert($external_tx);
    }
}
