# Dockerfile
FROM node:12.14.0
LABEL org.opencontainers.image.authors="Globalsys.co"

RUN mkdir /usr/src/app 
 
WORKDIR /usr/src/app

# Instalamos angular cli en nuestra imágen
RUN npm install -g @angular/cli 
