export interface ReconciliationItem{
    id: number
    bankId: number
    companyId: number
    accType: string
    bankAccount: string
    localAccount: string
    mapId: number
    deletedAt: any
    createdAt: any
    updatedAt: any
    accountId: number
    process: string
    startDate: string
    endDate: string
    externalDebit: string
    externalCredit: string
    localDebit: string
    localCredit: string
    externalBalance: string
    localBalance: string
    difference: string
    status: string
    step: string
    type: string
    codComp: string
    name: string
    nit: string
    currency: string
    portal: string  
}
